### ISSUE TITLE
when run "python train.py"，Run error display:TypeError: pic should be PIL Image or ndarray. Got <class 'NoneType'>

### ISSUE THREAD

**Issue by fittiing** [bobo0303/LIGHTWEIGHT-IMAGE-INPAINTING-BY-STRIPE-WINDOW-TRANSFORMER-WITH-JOINT-ATTENTION-TO-CNN#5]
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    for val_it, val_items in enumerate(loader):
  File "/public/home/zq_xuyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/public/home/zq_xuyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/public/home/zq_xuyan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/public/home/zq_xuyan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/public/home/zq_xuyan/perl5/lightweight/dataset.py", line 156, in __getitem__
    mask = self.to_tensor(mask)
  File "/public/home/zq_xuyan/perl5/lightweight/dataset.py", line 99, in to_tensor
    img_t = F.to_tensor(img).float()
  File "/public/home/zq_xuyan/.local/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 140, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'NoneType'>

**Comment by bobo0303** [comment]
It seems to be a problem when preparing the image files. Is there any more information you can provide?
